default:
  image: node:18.13.0

deploy_preview:
  stage: deploy
  except:
    - master
    - hotfix/final-contest
  script:
    - cd front
    - touch .env
    - echo NEXT_PUBLIC_KAKAO_JS_SDK_KEY=$NEXT_PUBLIC_KAKAO_JS_SDK_KEY >> .env
    - echo NEXT_PUBLIC_KAKAO_REDIRECTURI=$NEXT_PUBLIC_KAKAO_REDIRECTURI >> .env
    - echo NEXT_PUBLIC_LOGIN_REDIRECTURI=$NEXT_PUBLIC_LOGIN_REDIRECTURI >> .env
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN
deploy_production:
  stage: deploy
  only:
    - master
    - hotfix/final-contest
  script:
    - cd front
    - touch .env
    - echo NEXT_PUBLIC_KAKAO_JS_SDK_KEY=$NEXT_PUBLIC_KAKAO_JS_SDK_KEY >> .env
    - echo NEXT_PUBLIC_KAKAO_REDIRECTURI=$NEXT_PUBLIC_KAKAO_REDIRECTURI >> .env
    - echo NEXT_PUBLIC_LOGIN_REDIRECTURI=$NEXT_PUBLIC_LOGIN_REDIRECTURI >> .env
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN