server:
  port: 8080
  ssl:
    enabled: false

spring:
  profiles:
    include: aws
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  # API id for MSA
  application:
    name: ssarijileo-service

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/ssarijileo?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    url: jdbc:mysql://i8b302.p.example.io:3306/ssarijileo?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: example
    password: example

  # JPA Properties
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

  #redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6379

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# log level setting
logging:
  level:
    root: info
    com:
      example: debug

## eureka setting
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

# feign
feign:
  hystrix:
    enabled: true

