server:
    port: 8070
    ssl:
        enabled: false

spring:
    # MySQL
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #    url: jdbc:mysql://localhost:3306/ssarijileo?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
        url: jdbc:mysql://i8b302.p.example.io:3306/ssarijileo?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
        username: example
        password: example
    # JPA Properties
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                show_sql: true
    #redis
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379
        url: redis://localhost:6379

# feign
feign:
    hystrix:
        enabled: true